name: emergency_mesh_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- YOUR 5 TOOLS ---
  flutter_blue_plus: ^1.31.13    # The "Ears" (Scanning)
  flutter_ble_peripheral: ^1.2.1  # The "Mouth" (Advertising) - THIS IS THE FIX
  permission_handler: ^11.3.1   # For asking for permissions
  provider: ^6.1.2           # The "glue" to your teammate
  uuid: ^4.4.0               # For generating unique packet IDs
  # --- END YOUR TOOLS ---

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true