name: emergency_mesh_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- YOUR 4 CORE TOOLS ---
  flutter_blue_plus: ^1.31.13    
  flutter_ble_peripheral: ^1.2.1  
  permission_handler: ^11.3.1   
  uuid: ^4.4.0               
  geolocator: ^12.0.0
  
  # --- NEW "OPEN IN MAPS" PACKAGE ---
  url_launcher: ^6.3.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true